### ISSUE TITLE
Steam downloads

### ISSUE THREAD

**Issue by efinskiy** [itdoginfo/allow-domains#31]
После настройки кваса заметил что значительно упала скорость скачивания в Steam, до 100мбит, хотя мой тариф 1гбит.
Через Wireshark выцепил IP адреса к которым обращается стим при загрузке.
Удаление следующих адресов помогло исправить "замедление":

```
139.45.228.1
87.245.208.52
139.45.224.73
```

```
ipset del unblock 139.45.224.73
ipset del unblock 139.45.228.1
ipset del unblock 87.245.208.52
```

**Comment by efinskiy** [comment]
В причины попадания этих адресов в ipset не разбирался, но могу предположить что, они попадают туда при парсинге ip адресов сайтов, данные ip адреса пренадлежат IX провайдеру - RETN

**Comment by itdoginfo** [comment]
Квас просто идёт по всему списку и всё резолвит. Вам нужно найти домены, которые резолвятся в эти IP-адреса и удалить их. Если вдруг эти домены попали в список по ошибке, переоткройте, я удалю их из списка.
