### ISSUE TITLE
Add alza.hu and alza.cz online shops to "inside" lists

### ISSUE THREAD

**Issue by cyrmax** [itdoginfo/allow-domains#36]
There is a Czech online store alza.cz which also has a Hungarian version alza.hu.
They are blocking requests from Russia "as a part of security check and protection".
So the website technically opens but shows a single block page and does nothing more.

Please add these websites to an inside list.

**Comment by itdoginfo** [comment]
I don't see a problem with the alza.cz. 
alza.hu site has been added. 
Re-open if it doesn't work and attached screenshots.
