### ISSUE TITLE
Новые два домена в Россию

### ISSUE THREAD

**Issue by fatyzzz** [itdoginfo/allow-domains#4]
Clash Royale - 
clashroyaleapp.com
clashroyale.com

**Comment by itdoginfo** [comment]
https://github.com/itdoginfo/allow-domains?tab=readme-ov-file#%D0%BA%D0%B0%D0%BA-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B4%D0%BE%D0%BC%D0%B5%D0%BD%D1%8B-%D0%B2-%D1%81%D0%BF%D0%B8%D1%81%D0%BA%D0%B8

Прочитайте
