### ISSUE TITLE
Удалить из списков Inside домены howlongtobeat.com и ign.com

### ISSUE THREAD

**Issue by ProsWeb** [itdoginfo/allow-domains#40]
Удалить из списков Inside домены howlongtobeat.com и ign.com, т.к. их владелец передумал их блокировать для России.
Пруфы:
- https://dtf.ru/gameindustry/3013058-saity-ign-i-how-long-to-beat-vnov-stali-dostupny-iz-rossii
- https://howlongtobeat.com/forum/thread/3/217

**Comment by itdoginfo** [comment]
Done 6b7245bdeca07dbf28dbcb31dfe6ffa8664ffb71
