### ISSUE TITLE
*t.co домен в списке КВАСа влечет "блокировку" закачек в Steam

### ISSUE THREAD

**Issue by amorphine** [itdoginfo/allow-domains#48]
Текущий  КВАС работает с патченным dnsmasq
и вот этот entry` *t.co`
затрагивает вот такие домены
```
edgenext.cdn.steampipe.steamcontent.com
alibaba.cdn.steampipe.steamcontent.com
и прочие *steamcontent.com
```
В результате чего закачка идет "в блокировку"
След версия КВАСа перейдет на opkg-шный dnsmasq, и проблема должна уйти.
Пока предлагаю заменить` *t.co` на `t.co`

**Comment by itdoginfo** [comment]
1db8a76f1c037fae14f882418d2c37ab38930998
Сделал, спасибо
